# Generated by Django 4.0.3 on 2022-04-14 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.videopath')),
                ('keyword', models.CharField(max_length=10)),
                ('expose', models.IntegerField()),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
    ]
