# Generated by Django 3.2.13 on 2022-04-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.authuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='head_video',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded/Video'),
        ),
    ]
